apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lovetest-mbti

metadata:
  name: mbti-personality-test
  namespace: lovetest-mbti

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- env-configmap.yaml
- hpa.yaml

images:
- name: omaticaya/lovetest-mbti
  newTag: 1.0.1

commonLabels:
  app: mbti-personality-test
  managed-by: argocd

